### ISSUE TITLE
Error: enroll failed: POST failure of request:

### ISSUE THREAD

**Issue by rohitshukla11** [adityajoshi12/hyperledger-fabric-on-kubernetes#1]
Hi I am getting following error by running "kubectl hlf ca register --name=org1-ca --user=org1-peer1 --secret=peerpw --type=peer --enroll-id enroll --enroll-secret=enrollpw --mspid=Org1MSP --namespace=fabric" this command:
Error: enroll failed: enroll failed: POST failure of request: POST https://35.222.187.229:30635/enroll
{"hosts":[],"certificate_request":"-----BEGIN CERTIFICATE REQUEST-----\nMIHKMHICAQAwEDEOMAwGA1UEAxMFYWRtaW4wWTATBgcqhkjOPQIBBggqhkjOPQMB\nBwNCAAT3ocnPxKu6IRkNxFzgf8lVSzfWoWac7XnB926YrCihqESTc0YeA3L0X/fm\nLtrqkFusDdd+3wkaTD4X+iR+mSYToAAwCgYIKoZIzj0EAwIDSAAwRQIhAPSvvatJ\n8fTOHTZTs4MShyCoa+isfkER77uK5JcV4JdeAiA7LPcTRzMBN/bBp9ZbnQDRRpsz\nihMwBMhANgOaBZPYtQ==\n-----END CERTIFICATE REQUEST-----\n","profile":"","crl_override":"","label":"","NotBefore":"0001-01-01T00:00:00Z","NotAfter":"0001-01-01T00:00:00Z","ReturnPrecert":false,"CAName":"ca"}: Post "https://35.222.187.229:30635/enroll": dial tcp 35.222.187.229:30635: connect: connection timed out

**Comment by rohitshukla11** [comment]
Fixed

**Comment by Araj28196** [comment]
hi @rohitshukla11 
i am currently facing same issue

root@ubuntu-s-2vcpu-4gb-amd-blr1-01:~/bevel-operator-fabric# kubectl hlf ca register --name=org1-ca --user=org1-peer1 --secret=peerpw --type=peer --enroll-id enroll --enroll-secret=enrollpw --mspid=Org1MSP --namespace=fabric
 [fabsdk/fab] 2023/10/02 19:36:26 UTC - logbridge.(*cLogger).Info -> INFO TLS Enabled
 [fabsdk/fab] 2023/10/02 19:36:26 UTC - logbridge.(*cLogger).Info -> INFO generating key: &{A:ecdsa S:256}
 [fabsdk/fab] 2023/10/02 19:36:26 UTC - logbridge.(*cLogger).Info -> INFO encoded CSR
Error: POST failure of request: POST https://64.227.164.113:30884/enroll
{"hosts":null,"certificate_request":"-----BEGIN CERTIFICATE REQUEST-----\nMIIBBzCBrwIBADARMQ8wDQYDVQQDEwZlbnJvbGwwWTATBgcqhkjOPQIBBggqhkjO\nPQMBBwNCAAT5d4r4RvdZLE1ri1OH9lroq3LQ1Qgk4EM3+EUwBw0xirL1FsWA5FGC\nInjDO/lnc0f6jC6EYXM8V7WXGzeTYDrAoDwwOgYJKoZIhvcNAQkOMS0wKzApBgNV\nHREEIjAggh51YnVudHUtcy0ydmNwdS00Z2ItYW1kLWJscjEtMDEwCgYIKoZIzj0E\nAwIDRwAwRAIgOrkye0ACCLkoHzafwTniVAeAE2MJBNf2Cu9r9IzEClACIFYElcV8\nD8B7TKFccE08zAp7fFF5lgE7G89mrarbnNje\n-----END CERTIFICATE REQUEST-----\n","profile":"","crl_override":"","label":"","NotBefore":"0001-01-01T00:00:00Z","NotAfter":"0001-01-01T00:00:00Z","ReturnPrecert":false,"CAName":""}: Post "https://64.227.164.113:30884/enroll": x509: certificate is valid for 127.0.0.1, not 64.227.164.113

Please let us know how you solved
i am currently using digital ocean as my cloud platform and till CA everything worked
but error started on registering peer
I have checked firewall rules and updated them
still trying to figure out how to use tls certs here which may be what is required
